stages:
  - build
  - deploy

build website:
  image: node:21-alpine3.18
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy website:
  image: node:21-alpine3.18
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - apk add --no-cache git
    - npm install
    - npm install -g vercel
    - vercel deploy --prod --token $VERCEL_TOKEN --name canoapp --yes
  environment:
    name: production
